package main

// go:generate go-bindata -prefix ${PWD} -debug -tags "debug" -o "bindata_debug.go" data/...
// go:generate go-bindata -prefix ${PWD} -nomemcopy -tags "!debug" -o "bindata_release.go" data/...
