// Code generated by go-bindata.
// sources:
// data/help/config
// data/help/download
// data/help/help
// data/reference/eng
// data/reference/example
// data/web/favicon.ico
// data/web/templates/403.tpl
// data/web/templates/layout.tpl
// data/web/templates/node-children.tpl
// data/web/templates/node-content.tpl
// DO NOT EDIT!

// +build !release

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// dataHelpConfig reads file data from disk. It returns an error on failure.
func dataHelpConfig() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/help/config"
	name := "data/help/config"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataHelpDownload reads file data from disk. It returns an error on failure.
func dataHelpDownload() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/help/download"
	name := "data/help/download"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataHelpHelp reads file data from disk. It returns an error on failure.
func dataHelpHelp() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/help/help"
	name := "data/help/help"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataReferenceEng reads file data from disk. It returns an error on failure.
func dataReferenceEng() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/reference/eng"
	name := "data/reference/eng"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataReferenceExample reads file data from disk. It returns an error on failure.
func dataReferenceExample() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/reference/example"
	name := "data/reference/example"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataWebFaviconIco reads file data from disk. It returns an error on failure.
func dataWebFaviconIco() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/web/favicon.ico"
	name := "data/web/favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataWebTemplates403Tpl reads file data from disk. It returns an error on failure.
func dataWebTemplates403Tpl() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/web/templates/403.tpl"
	name := "data/web/templates/403.tpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataWebTemplatesLayoutTpl reads file data from disk. It returns an error on failure.
func dataWebTemplatesLayoutTpl() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/web/templates/layout.tpl"
	name := "data/web/templates/layout.tpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataWebTemplatesNodeChildrenTpl reads file data from disk. It returns an error on failure.
func dataWebTemplatesNodeChildrenTpl() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/web/templates/node-children.tpl"
	name := "data/web/templates/node-children.tpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataWebTemplatesNodeContentTpl reads file data from disk. It returns an error on failure.
func dataWebTemplatesNodeContentTpl() (*asset, error) {
	path := "/home/jonathan/workspace/ldss/data/web/templates/node-content.tpl"
	name := "data/web/templates/node-content.tpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/help/config": dataHelpConfig,
	"data/help/download": dataHelpDownload,
	"data/help/help": dataHelpHelp,
	"data/reference/eng": dataReferenceEng,
	"data/reference/example": dataReferenceExample,
	"data/web/favicon.ico": dataWebFaviconIco,
	"data/web/templates/403.tpl": dataWebTemplates403Tpl,
	"data/web/templates/layout.tpl": dataWebTemplatesLayoutTpl,
	"data/web/templates/node-children.tpl": dataWebTemplatesNodeChildrenTpl,
	"data/web/templates/node-content.tpl": dataWebTemplatesNodeContentTpl,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"help": &bintree{nil, map[string]*bintree{
			"config": &bintree{dataHelpConfig, map[string]*bintree{}},
			"download": &bintree{dataHelpDownload, map[string]*bintree{}},
			"help": &bintree{dataHelpHelp, map[string]*bintree{}},
		}},
		"reference": &bintree{nil, map[string]*bintree{
			"eng": &bintree{dataReferenceEng, map[string]*bintree{}},
			"example": &bintree{dataReferenceExample, map[string]*bintree{}},
		}},
		"web": &bintree{nil, map[string]*bintree{
			"favicon.ico": &bintree{dataWebFaviconIco, map[string]*bintree{}},
			"templates": &bintree{nil, map[string]*bintree{
				"403.tpl": &bintree{dataWebTemplates403Tpl, map[string]*bintree{}},
				"layout.tpl": &bintree{dataWebTemplatesLayoutTpl, map[string]*bintree{}},
				"node-children.tpl": &bintree{dataWebTemplatesNodeChildrenTpl, map[string]*bintree{}},
				"node-content.tpl": &bintree{dataWebTemplatesNodeContentTpl, map[string]*bintree{}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

